[project]
name = "backend"
version = "0.1.0"
description = "Assistant0: An AI Personal Assistant Secured with Auth0 - LangGraph Python/FastAPI Version"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "auth0-ai-langchain>=1.0.0b3",
    "auth0-fastapi>=1.0.0b4",
    "fastapi[standard]>=0.116.1",
    "google-api-python-client>=2.181.0",
    "httpx>=0.28.1",
    "itsdangerous>=2.2.0",
    "langchain-openai>=0.3.33",
    "langgraph-cli[inmem]>=0.4.2",
    "langgraph>=0.6.7",
    "pydantic-settings>=2.10.1",
]
