[project]
name = "backend"
version = "0.1.0"
description = "Assistant0: An AI Personal Assistant Secured with Auth0 - LangGraph Python/FastAPI Version"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "auth0-fastapi>=1.0.0b4",
    "fastapi[standard]>=0.115.14",
    "google-api-python-client>=2.176.0",
    "httpx>=0.28.1",
    "itsdangerous>=2.2.0",
    "langchain-openai>=0.3.28",
    "langgraph>=0.5.4",
    "langgraph-cli[inmem]>=0.3.6",
    "langgraph-api==0.2.102",
    "langgraph-runtime-inmem==0.6.0",
    "auth0-ai-langchain",
    "pydantic-settings>=2.10.1",
]

[tool.uv.sources]
auth0-ai-langchain = { path = "../../../../temp-packages/auth0-ai-langchain", editable = true }
